# This Makefile is part of the NUPACK software suite
# Copyright (c) 2007 Caltech. All rights reserved.
# Coded by: Justin Bois 1/2007
#
# Makefile for making all of NUPACK
#
# The src/thermo and src/shared directory is made.


all: 	
	$(MAKE) -C src/

clean: 
	$(MAKE) -C lib/ clean
	$(MAKE) -C src/ clean
	

